CREATE TABLE Turmas (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nome VARCHAR(100) NOT NULL
);

CREATE TABLE Alunos (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100),
    TurmaId INT NOT NULL,
    CONSTRAINT FK_Turma_Aluno FOREIGN KEY (TurmaId) REFERENCES Turmas(Id)
);